# When code hits the 'stage' branch, the code is stable and being tested for Prod.

trigger:
- stage

name: L_$(Date:yyyyMMdd)$(Rev:.r)__alpha
pool:
  name: default

stages: # Build - Test - *Deploy*
- stage: "BuildAndTest"
  jobs:
    - job: "Build"
      pool:
        name: "default"
        VmImage: "windows-latest"
      
      steps:
        - task: NodeTool@0
          inputs:
            versionSpec: '16.14.2'
          displayName: 'Install Node.js'

        - script: |
            cd client
            npm install
          displayName: 'npm install'
        
        - script: |
            cd client
            npm run build
          displayName: 'npm build'
          condition: succeeded()
        
        - script: |
            cd client
            npm test -- --watchAll=false
          displayName: "npm test"
          condition: succeeded()

        - task: CopyFiles@2
          inputs:
            Contents: 'client/build/**' # Pull the build directory (React)
            TargetFolder: '$(Build.ArtifactStagingDirectory)'

        - task: PublishBuildArtifacts@1
          inputs: 
            PathtoPublish: $(Build.ArtifactStagingDirectory)
            ArtifactName: 'www' # output artifact named www